### ISSUE TITLE
Wrong end date when using international day formats

### ISSUE THREAD

**Issue by ajgw** [woothemes/woocommerce-accommodation-bookings#11]
In Basket Accommodation shows ever the wrong enddate which base is January 1st 1970. It adds the bookings night to 1st and show in case of 4 nights duration January 5th 1970 as enddate. This is on site with german language and german date format: j. F Y

WC 2.5.1, Bookings 1.9.4, Accommodations 1.0.2 downloaded as master from github.

**Comment by ajgw** [comment]
I checked this on a different site were language is set to english in Wordpress and it works with all plugins I need – no bug on enddate. 
Checked on a third site were language is set to german in Wordpress set and I have the wrong enddate in 1970th.

**Comment by ajgw** [comment]
Checked again on german site: set in Wordpress Settings dateformat to m/d/Y I get this:
Check-in: 01/27/2016 at 16:00
Check-out: 01/31/2016 at 10:00

If I set dateformat either which language I selected in Wordpress Settings to j. F Y I get this:
Check-in: 27. Januar 2016 at 16:00
Check-out: 5. Januar 1970 at 10:00

Dateformat Y-m-d works too, but all other dateformat settings shows wrong enddate of booking.

**Comment by mikeyarce** [comment]
I was able to reproduce the issue on my site.  Steps to reproduce:
1. Change the Date Format in Settings > General to `j, F Y`
2. Make sure you specify Check-in/Check-out times in WooCommerce > Settings > Products > Accommodations
3. Add an Accommodation to your Cart
Result:
![screen shot 2016-01-27 at 1 24 39 pm](https://cloud.githubusercontent.com/assets/3220162/12628715/58d35e48-c4f9-11e5-88a4-3fac3d5e6f1a.png)

cc @justinshreve @BFTrick

**Comment by ajgw** [comment]
Not only in cart but in emails too.

**Comment by solaceten** [comment]
I had this issue.  In the end I deleted woocommerce, woocommerce-booking and the accommodation addon plugin - then re-installed them all and the problem was gone.

**Comment by ajgw** [comment]
In my case it was a fresh set up with WC 2.5, Bookings 1.9.3 and Accommodations 1.0.1

**Comment by gedex** [comment]
Another fix for this in #19.
