### ISSUE TITLE
couple of improvements

### ISSUE THREAD

**Issue by solaceten** [woothemes/woocommerce-accommodation-bookings#12]
Thanks for releasing this much needed addon.

1) On the booking page it says "Booking Date: *****

This currently seems to show the start date of the booking.  Is that intentional, or should it be "Today"  as in the date the booking is being made?

2) Also, there does not seem to be an easy way to add a discount or supplement for e.g. a one night stay.

I imagine this could be as simple as adding an additional field in the "Rates" row? Something along the lines of Range of Number of Nights - this will allow users to add a discount or supplement accordingly?

As an temp fix, I came up with the following, and have added it  to woocommerce-bookings/includes/class-wc-booking-form.php - however it's not working quite right - can you take a look?

                // Around Line 870
               // Person multiplier mutliplies all costs
		$this->booking_cost = max( 0, $total_block_cost + $base_cost );

       // this added to add a single night supplement cost of $20				
		
		$booking_duration = $this->product->wc_booking_duration;
		$singlesupp  = '20.00';
		
			 if ( $booking_duration ==1 ) {
					$this->booking_cost = $this->booking_cost + $singlesupp; 
					 }'

I just need this to work until your next update that will hopefully include this feature.
Thank you

**Comment by TomasHurtz** [comment]
@solaceten The possibility a discount after x days as well we need. I tried the above fix but this not work for me if pricing rules are on place in product, but worked if no rules.

**Comment by solaceten** [comment]
Issue one is resolved - thank you :-)

Any chance in 1.02 to get a look at adding the ability to add or subtract fees based on number of nights?  In my case I need a single night supplement - I was not able to do it correctly.

An additional field in the "Rates Rules" table would be awesome.

**Comment by gedex** [comment]
> 1) On the booking page it says "Booking Date: *****
>
> This currently seems to show the start date of the booking. Is that intentional, or should it be "Today" as in the date the booking is being made?

By booing page, I assumes this view order page with accommodation-booking product. Good catch, I believe booking date should be the date when an order is created. Will change that.

> 2) Also, there does not seem to be an easy way to add a discount or supplement for e.g. a one night stay.
>
> I imagine this could be as simple as adding an additional field in the "Rates" row? Something along the lines of Range of Number of Nights - this will allow users to add a discount or supplement accordingly?
>
> As an temp fix, I came up with the following, and have added it to woocommerce-bookings/includes/class-wc-booking-form.php - however it's not working quite right - can you take a look?

This would be enhancement, but not for 1.0.2.

**Comment by gedex** [comment]
@solaceten I separate your improvements into two separate issues in #28 and #29. This would help us to close related issue with one PR. Closing this.

**Comment by solaceten** [comment]
Hi @gedex - thanks for the update.

I understand about separating the issues and to work on #29 later - is there any chance you can help with improving my temporary hack - so that it can be used in the meantime?  Or - is there a hook I could use? 

My code [copied below] does work, but not when there are other additional rules (such as certain rates for a range of months).

> Added as a hack to woocommerce-bookings/includes/class-wc-booking-form.php 

            // Around Line 870
           // Person multiplier mutliplies all costs
    $this->booking_cost = max( 0, $total_block_cost + $base_cost );

   // this added to add a single night supplement cost of $20               

    $booking_duration = $this->product->wc_booking_duration;
    $singlesupp  = '20.00';

         if ( $booking_duration ==1 ) {
                $this->booking_cost = $this->booking_cost + $singlesupp; 
                 }'

I see there is a function process_cost_rules and a variable $override_block 

What do I need to adjust in order for this to work when there are also Rate Rules ?

**Comment by solaceten** [comment]
OK I got the following to work - i know it's a dirty hack that the developers may strongly disapprove of, but it works for now - feel free to suggest improvements.

```
`$booking_length = $data['duration'];
		$override_block = apply_filters( 'woocommerce_bookings_process_cost_rules_override_block', ( isset( $fields['override_block'] ) ? $fields['override_block'] : '' ), $fields, $key );
		$cost = apply_filters( 'woocommerce_bookings_process_cost_rules_cost', $fields['cost'], $fields, $key );
		$singlesupp  = '20.00';
		
			 if ( $booking_length ==1 ) {
					// $this->booking_cost = $block_cost + $singlesupp; 
					
					$this->booking_cost = $total_block_cost + $base_cost + $override_block + $cost + $singlesupp;  
					
					 } `
```
