### ISSUE TITLE
Unable to re-order rate rules

### ISSUE THREAD

**Issue by solaceten** [woothemes/woocommerce-accommodation-bookings#26]
When a Product is an Accommodation type I am unable to re-order the rate rules.  

Edit Product > Product Data > Rates > Click the rate to move - unable to drag it to move it.

![edit product prioritise rates - ajax failure](https://cloud.githubusercontent.com/assets/2679075/13008297/cf8e88e8-d195-11e5-8558-d5b01631231c.png)

**Comment by al3xstanhope** [comment]
I've noticed this one too! Running Bookings v1.9.5 and Accommodation Bookings v1.02 here :(
