### ISSUE TITLE
Range of Months don't appear to span year end

### ISSUE THREAD

**Issue by solaceten** [woothemes/woocommerce-accommodation-bookings#32]
In the Rate Rules, for example adding a rule: October - April encountered an error that the Rate Rule doesn't appear to calculate correctly after the year end - instead I had to make two rate rules October - December and then January - April.  Can you duplicate this on your side?
See attached

![rate-rule-issue](https://cloud.githubusercontent.com/assets/2679075/13083964/96daa69a-d4d7-11e5-9a25-3215ce982d45.png)

**Comment by dwainm** [comment]
Thanks for reporting @solaceten. This issue can't be fixed within the accomodation plugin. I've created a new issue on the core bookings extension which will be looked at as soon as possible.
