### ISSUE TITLE
compatibility with Product Add-ons

### ISSUE THREAD

**Issue by WillBrubaker** [woothemes/woocommerce-accommodation-bookings#34]
Any product add-on will double its own cost once added to the cart.

screenshots:
Addon Configuretion: http://cld.wthms.co/Nguy/KFI1DFKa
Price calculation on the product page, with addon selected: http://cld.wthms.co/SbWa/3bhgAEVO
Price after added to cart: http://cld.wthms.co/18cmH/2WXNYO6B

Ticket here: 386324-zd-woothemes

@gedex

**Comment by BFTrick** [comment]
@WillBrubaker - just to confirm - does this only happen with accommodations and not bookings?

**Comment by WillBrubaker** [comment]
@BFTrick - yes only happens with accommodations.

**Comment by adrienromain** [comment]
@BFTrick @WillBrubaker @gedex Hello, I confirm the problem with the Woocommerce Product-Addons, total options is added double when passing to cart. Thank you for solving bug in next 1.0.3...

**Comment by al3xstanhope** [comment]
I too can confirm the existence of this particular issue on Bookings v1.9.5 and Accommodation Bookings 1.0.2 and Product Add-ons 2.7.16 - hopefully you guys will fix it soon!
