### ISSUE TITLE
Hide shipping tab

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce-accommodation-bookings#35]
It does not make sense to have the Shipping tab in Product data for this kind of product.

I think they are supposed to always be virtual, right?

**Comment by gedex** [comment]
Unable to reproduce when product is Accommodation Product.

![screenshot](https://cldup.com/VNDcob9dAc.png)

**Comment by gedex** [comment]
Please reopen in case you've specific steps to reproduce.

**Comment by SiR-DanieL** [comment]
I don't know how to reproduce but I tried this

* I reset my local WordPress installation
* Install WooCommerce and go through the Wizard
* Install WooCommerce Bookings and WooCommerce Accomodation Bookings
* Create a new product
* Set a title
* Change the type to Accomodation
* The shipping tab is there

**Comment by gedex** [comment]
@SiR-DanieL Per our discussion in Slack it seems expected JS is not loaded.
