### ISSUE TITLE
Plugin on WordPress.org does not include assets folder

### ISSUE THREAD

**Issue by robertstaddon** [woothemes/woocommerce-accommodation-bookings#39]
If you go to https://wordpress.org/plugins/woocommerce-accommodation-bookings/ and download this plugin from the WordPress repository, the downloaded zip file (https://downloads.wordpress.org/plugin/woocommerce-accommodation-bookings.latest-stable.zip) does not contain the "assets" folder.

This generates "Not found" errors for the "assets/js/writepanel.min.js" file in the browser console as described in this support post: https://wordpress.org/support/topic/jsver102-404-not-found?replies=1

**Comment by robertstaddon** [comment]
I've created a pull request that completely gets rid of the writepanel.js altogether, which isn't needed if the classes are named correctly. It also allows Accommodatiosn to use the Resources feature of WooCommerce Bookings. https://github.com/woothemes/woocommerce-accommodation-bookings/pull/40

**Comment by dwainm** [comment]
@robertstaddon thanks for the effort on the PR. I know the effort has gone into this already, but could you please separate the issue within your PR? 

1) The assets directory not being included is possibly due to a deploy error which we should fix there
2) Using resources is an issue for separate consideration. I'd appreciate it if remove the writepanel.js file is not part of the solution. I'll be happy to inspect the PR when updated.

**Comment by robertstaddon** [comment]
Thank you, @dwainm. You are correct that the plugin from the WordPress repository (https://wordpress.org/plugins/woocommerce-accommodation-bookings/) could be easily fixed simply by adding an assets folder, which was probably caused by a deploy error. You can verify this by looking at line 51 of the "/woocommerce-accommodation-bookings/includes/admin/class-wc-accommodation-booking-admin-panels.php" file, which is trying to enqueue a script that doesn't exist in the WordPress repository package: WC_ACCOMMODATION_BOOKINGS_PLUGIN_URL . '/assets/js/writepanel'

The assets folder does exist on the GitHub site at https://github.com/woothemes/woocommerce-accommodation-bookings  It's a shame this hasn't been redeployed yet, as anyone trying out this wonderful little plugin will be experiencing console script errors. A simple repackage and redeploy should be simple to do.

--

The real intent of my PR is to allow the Resources feature to be used with WooCommerce Bookings. As I was working on making this happen, I ran into a couple bugs that were a result of the Accommodations Bookings plugin hacking together some show/hide code in it's own writepanel.js file instead of using the official WooCommerce means of showing and hiding panels.

If you look at the "show_and_hide_panels()" function in "woocommerce/assets/js/admin/meta-boxes-product.js", you'll see that the way panels are *supposed* to be shown and hidden in WooCommerce is with a '.show_if_' + product_type string. 

        $( '.show_if_' + product_type ).show();

	$( '.hide_if_' + product_type ).hide();

We know that the WooCommerce product type for an Accommodation Booking is "accommodation-booking" (note the dash vs. an underscore). Therefore the class that should be assigned to the panels we want to show and hide using Accommodation Bookings is "show_if_accommodation-booking" and "hide_if_accommodation-booking". Once this is understood, showing and hiding panels is simple. 

The existing plugin was using "show_if_accommodation_booking" and "hide_if_accommodation_booking" classes (note the underscores) and was then then forced to hack together some custom show/hide code in a writepanel.js file. This wasn't robust enough to support adding the Resources panel, which is what I was trying to do. However, giving the correct class names resolves this issue and allows us to clean up the unneeded code in writepanel.js  Therefore, removing the code in this file is an essential part of adding Resources support, which was the intent of my PR.

**Comment by dwainm** [comment]
Thank you @robertstaddon one of our developers will inspect your PR and provide feedback as soon as possible. For now I've renamed the original issue #38 we are looking to bump the version number soon as there are some bugs that need to be deployed.
