### ISSUE TITLE
Per Night Price Displaying Incorrect Price

### ISSUE THREAD

**Issue by kristinaplauche** [woothemes/woocommerce-accommodation-bookings#41]
**Issue:** If the minimum number of nights allowed in a booking is set to anything greater than 1, the minimum number of nights is multiplied by the standard rate and displayed as the per night price on the product page. That price is incorrect.
@gedex 
**To replicate:**

Plugins enabled:  WooCommerce, WooCommerce Bookings, WooCommerce Accomodation Bookings

**Create a new product.**
 * Set product data to: Accommodation product.
 * In the [General section:](http://cld.wthms.co/MCeT/2Wg1AoRf) Set these fields: 
  * Minimum number of nights allowed in a booking: 2
  * Maximum number of nights allowed in a booking: 7 (could be any number greater than 2)
  * All other fields are unchanged from default.
 * In the [Rates section](http://cld.wthms.co/1fCon/1jaS8bdx)
  * Set Standard Room Rate to 150.00  (or any price)
 * Publish.

[View product.](http://cld.wthms.co/HjRy/sEyn2LWW)  
You will see that it now says "From $300.00 per night"  instead of $150.00 per night.
If you change minimum nights allowed to 1.  Then the product says "From $150.00 per night."
If you change minimum nights allowed to 5.  Then the product says "From $750.00 per night"
etc...

**Desired outcome:**
**Display per night price as the correct standard rate per night price.**

**Comment by gedex** [comment]
Thanks for the report @kristinaplauche. @dwainm Could you please investigate this?
