### ISSUE TITLE
Resource not calculating properly.

### ISSUE THREAD

**Issue by mixxxx00** [woothemes/woocommerce-accommodation-bookings#57]
The resource block cost is not adding according to the nights count.
Here are the issues listed below:
- Block cost not adding with the number of nights
- If base cost is used the the drop down resource menu is adding the base cost and block cost per night only in the drop down menu.

Thanks.

**Comment by robertstaddon** [comment]
Can you post a link to the site?

**Comment by mixxxx00** [comment]
Thanks for looking into the issue. Really appreciate your effort.

This is the link to the test page:
http://houseofkapaali.com/rooms/omkara/

Also i have noticed i more issue:
After a successful booking the Blocks are still available to book. It should be blocked to book further.

**Comment by mixxxx00** [comment]
Testing Addon: 
I have tried setting the range to make the resource available with "1" priority.
Still not adding.

**Comment by robertstaddon** [comment]
@mixxxx00, part of your problem may be related to #10 . Can you try switching your Calendar display mode to "Calendar always visible"?

Are you using Resources for your "Extra Bed & Breakfast"? I don't think that this is how Resources were intended to be used. Read the "Resources" section at this link for more information on Resources: https://docs.woothemes.com/document/creating-a-bookable-product/  A resource in your situation would be more along the lines of a type of room or specific rooms.

I would suggest using Product Add-ons for your "Extra Bed & Breakfast" option: https://www.woothemes.com/products/product-add-ons/

**Comment by mixxxx00** [comment]
Thanks @robertstaddon , I will look into the plugin and update.
Thanks again for your efforts

**Comment by mixxxx00** [comment]
Closing the issue as it is with Bookings Plugin Core.
