### ISSUE TITLE
When using date entry fields instead of the calendar, the price does not calculate.

### ISSUE THREAD

**Issue by robertstaddon** [woothemes/woocommerce-accommodation-bookings#58]
When using the default date entry with "Month" / "Day" / "Year" fields instead of the clickable calendar, the price is not automatically calculated when dates are entered. In fact, if you have no other form elements to trigger the price calculation (such as Persons or Resources), the "Book Now" button will remain grayed out and you will be unable to book at all.

**Comment by mixxxx00** [comment]
@robertstaddon are you going to repair the bug in your files?

**Comment by robertstaddon** [comment]
The actual cause of the issue is with WooCommerce Bookings. When we set the Booking duration to "Customer defined blocks" on a Bookable product and  "Enable Calendar Range Picker", the automatic JavaScript update is disabled when any fields are changed. 

This is triggered by lines 19-23 of the 'woocommerce-bookings/assets/js/booking-form.js' file:

`
			if ( $picker.data( 'is_range_picker_enabled' ) ) {
				if ( 'wc_bookings_field_duration' !== name ) {
					return;
				}
			}
`

The reason that this bug is most obvious with Accommodation Bookings is because it automatically sets the Booking product duration to "Customer defined blocks" and enables the Calendar Range Picker. The options aren't even presented on the admin panel because an accommodation would require them.

**Comment by mixxxx00** [comment]
@robertstaddon could you please tell: what code can be altered to fix this bug in woocommerce bookings plugin. 

Thanks

**Comment by robertstaddon** [comment]
I'm reporting this bug to WooThemes since it is with their WooCommerce Bookings plugin. To get around it, change your Calendar display mode to "Calendar always visible."

**Comment by roykho** [comment]
I am closing this as this will be addressed in the Bookings core. Thanks for reporting!

**Comment by mixxxx00** [comment]
@robertstaddon Product Addon is working as suggested by you. Thanks and a little update, my calendar is working fine without switching to "Calendar always visible".

Will report if i find any bug, Cheers

**Comment by robertstaddon** [comment]
WooThemes emailed me back today: "The bug has been fixed and will be available in the next release. There isn't a schedule for when that will be, but hopefully soon."
