### ISSUE TITLE
Better price control for Persons

### ISSUE THREAD

**Issue by jessepearson** [woothemes/woocommerce-accommodation-bookings#60]
Thanks for the awesome addition of adding Persons to Accommodations!

I found the update and had a use case to try out, but ran into a small snag that may cause users' customers to feel deceived with pricing. Use case is a room is 155 a night, and each additional (over 1 person) person is an additional 20 per night. 

This video outlines the whole issue:
http://cld.wthms.co/1dLzc/4yZdhmK2

#### What I expected

Ability to set persons at 20 per block per person. Then create a person range in Costs/Rates tab to be able to reduce the base cost 20 (for the first person), so the total cost is reflected accurately.

#### What happened instead

There is not a person range to be able to work with in Costs/Rates tab.

#### Steps to reproduce the issue

1. Set room rate at 155
1. Create persons, each block is 20
1. Save product, then view it
1. Create booking for one night, it will be 175
1. If rate is reduced to 135 to offset for person cost, then displayed rate is deceptive when it reads *From $135.00 per night*, when it's actually 155 per night once a person is added.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
Closed via https://github.com/woothemes/woocommerce-accommodation-bookings/pull/66/commits/69dfcddfd4ec3977031c57389e7a0a3661142eed
