### ISSUE TITLE
Change logic for dependecy check

### ISSUE THREAD

**Issue by andreas-pa** [woothemes/woocommerce-accommodation-bookings#63]
Hello to the team!

I would like to propose something about the dependency logic you have for WC Bookings plugin.

In file /includes/class-wc-accommodation-dependencies.php arount line 27we have :

```
private static function is_bookings_installed() {
		return in_array( 'woocommerce-bookings/woocommmerce-bookings.php', self::$active_plugins ) || array_key_exists( 'woocommerce-bookings/woocommmerce-bookings.php', self::$active_plugins );
	}
```

This function is checking in the folder `woocommerce-bookings` .

I think this is wrong because someone maybe would change the folder name to something else.

I think we should check with the main class of Bookings , `WC_Bookings` and not with the folder name.

What do you think?

Thank you very much for your time

**Comment by gedex** [comment]
@andreas-pa sounds good to me. I'm changing it for 1.0.6.
