### ISSUE TITLE
Calendar not honoring check in/out times

### ISSUE THREAD

**Issue by kristinaplauche** [woothemes/woocommerce-accommodation-bookings#69]
Reported in this ticket: [460956](https://woothemes.zendesk.com/agent/tickets/460956)
#### What I expected

To be able to book a check in date on the same day that the previous booking checked out and vice versa.

#### What happened instead

Can't select checkout date (11am) on a date where a customer booked a check in (3:00pm)

#### Steps to reproduce the issue

Check in time 3:00pm
Check out time 11:00am
Customer A books Sept 25-27th
Customer B tries to book Sept 23-25th, but can't because the 25th shows as fully booked.  But it's not.  Customer A can't check in until 3pm, so the room should be available until 11:00am.

![screenshot](http://cld.wthms.co/10b0y/52WC84iL+)
http://cld.wthms.co/10b0y/52WC84iL

I notice that the start time and end time are not entered into the booking itself.  
![screenshot](http://cld.wthms.co/13OlQ/58DWWX7M+)
http://cld.wthms.co/13OlQ/58DWWX7M

When the check in time is manually entered as the start time and the check out time is manually entered as the end time, then the calendar works as it should.

-------------------

- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by kristinaplauche** [comment]
@roykho Any chance I can get an ETA on this?  The basic functionality is compromised. I have an anxious user. Thanks!

**Comment by gedex** [comment]
@kristenzuck Can you pull `master` and see if it fixes the issue. Please note for existing booking, you need to update the time manually. But for new booking added to cart, start/end time will set correctly based on check in/out time.

**Comment by kristinaplauche** [comment]
@gedex That worked for me. Thank you!!!
