### ISSUE TITLE
PHP Warning in Plesk (php 5.6) 

### ISSUE THREAD

**Issue by shortsort** [woothemes/woocommerce-accommodation-bookings#70]
PHP Warning: include(/var/www/vhosts/website.de/httpdocs/wp-content/plugins/woocommerce-accommodation-bookings/includes/integrations/class-wc-accommodation-booking-addons.php): failed to open stream: No such file or directory in /var/www/vhosts/website.de/httpdocs/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-bookings-plugin.php on line 147\nPHP message: PHP Warning: include(): Failed opening '/var/www/vhosts/website.de/httpdocs/wp-content/plugins/woocommerce-accommodation-bookings/includes/integrations/class-wc-accommodation-booking-addons.php' ...
![error](https://cloud.githubusercontent.com/assets/21291959/18034154/f9730d64-6d35-11e6-8362-0b4ce5f48f48.png)

**Comment by roykho** [comment]
What version are you running and did you download the files again to see if that resolves your issue?

**Comment by shortsort** [comment]
1.0.5. Uploaded the same files again. After Uploading, it looks like the issue was resolved. How is it possible? Some file modifications?

**Comment by roykho** [comment]
If I remember correctly, there may have been a file that was not included in the deploy and was quickly fixed. So you may have downloaded it when that happened.
