### ISSUE TITLE
Fatal error when plugin is deactivated

### ISSUE THREAD

**Issue by roykho** [woothemes/woocommerce-accommodation-bookings#9]
So if you have accommodation bookings listed and then you go and deactivate the accommodations plugin and go back to the list, you will see a fatal error.

Also, I encountered a "permissions error" when I try to delete the accommodation bookings from the trash using "empty trash".  Although I think it does empty it after you see the "permissions error".

**Comment by justinshreve** [comment]
Closing in favor of https://github.com/woothemes/woocommerce-bookings/issues/592 which fixes this on the bookings side.
